### ISSUE TITLE
Capital letters

### ISSUE THREAD

**Issue by Loekie63** [FilipDem/Domoticz-NEST-plugin#41]
Hi, I cannot get your cde to work. I found my Domoticz folder is not with a capital D. Might this be the problem?

**Comment by FilipDem** [comment]
Don't know... Are other plugins working? If yes, it should be OK.
Anyway, nothing is done specifically in the plugin to refer to the Domoticz folder... This is normally one of the configuration parameters.

**Comment by Loekie63** [comment]
Then something else must be wrong as no devices ae created. Are devices created even when one of the codes, issue or cookie are not correct?

**Comment by Loekie63** [comment]
Other plugins are working fine (Tuya for instance). Then something else must be wrong as no devices are created. Does the plugin create devices even if one of the codes are not correct (issue or cookie) As it is not xplained in the readme just to be sure need the zip files Nest Heating.Zip and so on to be unzipped and placed unzipped in the plugin folder or do they need a separate folder whitin the plugin folder?

**Comment by FilipDem** [comment]
No... You need to activate the debug to see what is going on...

Op zo 6 aug. 2023 10:41 schreef Loekie63 ***@***.***>:

**Comment by Loekie63** [comment]
Everything worked for months. Now it works when I fill in the token and then stops working. Only "Outside Weather" keeps giving data. Errors in the log:
2024-01-31 17:30:48.531 Nest: > Finished handling task: StatusUpdate.
2024-01-31 17:30:48.531 Nest: > Handling task: OutsideWeather.
2024-01-31 17:30:48.782 Nest: > {"City": "Sittard", "Current_humidity": 66, "Current_temperature": 6.7, "Current_wind": 10, "Wind_direction": "SSW"}
2024-01-31 17:30:48.784 Nest: > Updated 2 units for weather.
2024-01-31 17:30:48.784 Nest: > Finished handling task: OutsideWeather.
2024-01-31 17:30:58.018 Nest: Pushing 'onHeartbeatCallback' on to queue
2024-01-31 17:30:58.068 Nest: Processing 'onHeartbeatCallback' message

**Comment by Loekie63** [comment]
And then the following appears:
2024-01-31 17:32:48.068 Nest: > Handling task: StatusUpdate.
2024-01-31 17:32:48.072 Nest: Acquiring GIL for 'onHeartbeatCallback'
2024-01-31 17:32:48.533 Nest: Unable to get update data from Nest (last error: API returned error: No active session found.).

**Comment by Loekie63** [comment]
When I udate the Token and Cookie the following pops up:
2024-01-31 17:36:26.545 Error: Nest: (GoogleNest) failed to load 'plugin.py', Python Path used was '/home/pi/domoticz/plugins/GoogleNest/:/usr/lib/python39.zip:/usr/lib/python3.9:/usr/lib/python3.9/lib-dynload:/usr/local/lib/python3.9/dist-packages:/usr/lib/python3/dist-packages:/usr/lib/python3.9/dist-packages'.
2024-01-31 17:36:26.557 Error: Nest: Traceback (most recent call last):
2024-01-31 17:36:26.557 Error: Nest: File "/home/pi/domoticz/plugins/GoogleNest/plugin.py", line 68, in <module>
2024-01-31 17:36:26.558 Error: Nest: import nest
2024-01-31 17:36:26.558 Error: Nest: File "/home/pi/domoticz/plugins/GoogleNest/nest.py", line 27, in <module>
2024-01-31 17:36:26.558 Error: Nest: import requests
2024-01-31 17:36:26.558 Error: Nest: File "/usr/local/lib/python3.9/dist-packages/requests/__init__.py", line 48, in <module>
2024-01-31 17:36:26.558 Error: Nest: from charset_normalizer import __version__ as charset_normalizer_version
2024-01-31 17:36:26.558 Error: Nest: File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/__init__.py", line 24, in <module>
2024-01-31 17:36:26.558 Error: Nest: from .api import from_bytes, from_fp, from_path, is_binary
2024-01-31 17:36:26.558 Error: Nest: File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/api.py", line 5, in <module>
2024-01-31 17:36:26.558 Error: Nest: from .cd import (
2024-01-31 17:36:26.558 Error: Nest: File "/usr/local/lib/python3.9/dist-packages/charset_normalizer/cd.py", line 14, in <module>
2024-01-31 17:36:26.558 Error: Nest: from .md import is_suspiciously_successive_range
2024-01-31 17:36:26.558 Error: Nest: AttributeError: PyCapsule_Import "charset_normalizer.md__mypyc.init_charset_normalizer___md" is not valid

**Comment by FilipDem** [comment]
I would assume you have an error in the copy/past of your token/Cookie as there are errors in the requests.

**Comment by Loekie63** [comment]
You assumed right. So i Looked up the right token/Cookie and updated them. It worked for 2 days and now I have the following:
Nest: Unable to get update data from Nest (last error: API returned error: No active session found.). and a lot of:
2024-02-02 18:50:50.086 Nest: Acquiring GIL for 'onHeartbeatCallback'
2024-02-02 18:50:50.086 Nest: Calling message handler 'onHeartbeat' on 'module' type object.
2024-02-02 18:50:50.086 Nest: Acquiring GIL for 'onHeartbeatCallback'
2024-02-02 18:51:00.005 Nest: Pushing 'onHeartbeatCallback' on to queue
2024-02-02 18:51:00.055 Nest: Processing 'onHeartbeatCallback' message
2024-02-02 18:51:00.055 Nest: Acquiring GIL for 'onHeartbeatCallback'
And this over and over again. Strange thing is the following works:
{"City": "MyCity", "Current_humidity": 88, "Current_temperature": 7.8, "Current_wind": 18, "Wind_direction": "SW"}
2024-02-02 18:52:20.992 Nest: > Updated 2 units for weather.
2024-02-02 18:52:20.992 Nest: > Finished handling task: OutsideWeather and then:
2024-02-02 18:50:50.086 Nest: Acquiring GIL for 'onHeartbeatCallback'
2024-02-02 18:50:50.086 Nest: Calling message handler 'onHeartbeat' on 'module' type object.
2024-02-02 18:50:50.086 Nest: Acquiring GIL for 'onHeartbeatCallback'
2024-02-02 18:51:00.005 Nest: Pushing 'onHeartbeatCallback' on to queue
2024-02-02 18:51:00.055 Nest: Processing 'onHeartbeatCallback' message
2024-02-02 18:51:00.055 Nest: Acquiring GIL for 'onHeartbeatCallback'
When I open the nest website I am still logged in.

**Comment by Loekie63** [comment]
I have a theory why this happens. Please let me know if you agree.
When i am connected thru Domoticz with this plugin and the valid Token/Cookie for that moment and I log in with the Nest app on my phone, The Token/Cookie changes, hence the one in Domoticz is not valid anymore.

**Comment by FilipDem** [comment]
Of course . I wanted to communicate it also to you that you should not do a
logout on device where you have taken the token. I had my pc/browser, app
on my mobile and domticz and all worked perfectly together. Now I sold my
house so I have don't have the Best thermostat anymore. In my new house all
is electric...

Op za 3 feb. 2024 11:00 schreef Loekie63 ***@***.***>:
